AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "script/**/*"
    - "vendor/**/*"

Metrics:
  Enabled: false

Naming/VariableNumber:
  CheckMethodNames: false
  CheckSymbols: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/Proc:
  Enabled: false
