name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        redmine_version: ["6.0-stable", "6.1-stable"]
    env:
      RAILS_ENV: test
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PGPASSWORD: postgres
      DATABASE_URL: postgresql://postgres:postgres@localhost/redmine_test
      REDMINE_VERSION: ${{ matrix.redmine_version }}

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout redmine repository
        uses: actions/checkout@v4
        with:
          repository: redmine/redmine
          path: redmine
          ref: ${{ matrix.redmine_version }}

      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          path: redmine/plugins/redmine_semantic_search
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Use plugin .ruby-version
        working-directory: redmine
        run: ln -s plugins/redmine_semantic_search/.ruby-version

      - name: Configure database
        working-directory: redmine
        run: cp plugins/redmine_semantic_search/config/database.yml.example config/database.yml

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: redmine
          bundler-cache: true

      - name: Setup database
        working-directory: redmine
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake redmine:load_default_data REDMINE_LANG=en
          bundle exec rake redmine:plugins:migrate

      - name: Run tests
        working-directory: redmine
        run: |
          bundle exec rake redmine:plugins:test NAME=redmine_semantic_search
